# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet pack --configuration Release
    - name: Add github source
      run: dotnet nuget add source --username Agarz4 --password ${{ secrets.PUBLISH_GITHUB_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Agarz4/index.json"
    - name: Push nuget to GitHub
      run: dotnet nuget push "D:\a\zaraga.logger\zaraga.logger\zaraga.logger\bin\Release\zaraga.logger.1.0.0.nupkg" --api-key --api-key ${{ secrets.PUBLISH_GITHUB_PAT }} --source github
    - name: Push nuget to NuGet.org
      run: dotnet nuget push "D:\a\zaraga.logger\zaraga.logger\zaraga.logger\bin\Release\zaraga.logger.1.0.0.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
